name: newproject

services:

# ========================================
# BACKEND - API Symfony
# ========================================
  backend-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev

    container_name: newproject-php
    restart: unless-stopped

    working_dir: /var/www/html

    depends_on:
      backend-postgres:
        condition: service_healthy
        restart: true

    networks:
      - newproject_network

    expose:
      - "9000"

    volumes:
      - .:/var/www/html
    
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@backend-postgres:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=18&charset=utf8
    
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

# ========================================
# BACKEND - NGINX (reverse proxy pour Symfony)
# ========================================
  backend-nginx:
    image: nginx:1.29.3
    container_name: newproject-nginx
    restart: unless-stopped

    depends_on:
      backend-php:
        condition: service_healthy

    networks:
      - newproject_network

    ports:
      - "8080:80"

    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    
    healthcheck:
      test: ["CMD-SHELL", "nginx -t >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3

# ========================================
# BACKEND - PostgreSQL
# ========================================
  backend-postgres:
    image: postgres:18
    container_name: newproject-postgres
    restart: unless-stopped

    networks:
      - newproject_network

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

# ========================================
# BACKEND - pgadmin
# ========================================
  backend-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: newproject-pgadmin
    restart: unless-stopped
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    
    ports:
      - "5050:80"
    
    networks:
      - newproject_network
    
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    
    depends_on:
      - backend-postgres

# ========================================
# NETWORKS
# ========================================
networks:
  newproject_network:
    driver: bridge
    name: newproject_network

# ========================================
# VOLUMES
# ========================================
volumes:
  postgres_data:
    name: newproject_postgres_data
  pgadmin_data:
    name: newproject_pgadmin_data